default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: fernando
  password:

development:
  <<: *default
  database: gobify-data_development

test:
  <<: *default
  database: gobify-data_test
